Code review: Testing the To-do list
Milypm/to-do-list-JS pull request #4
Opened 2021-05-29 22:07 UTC by Milypm

For this project, we implemented some testing methods.

The main categories are:
- Testing the logic for manipulating projects on localStorage
- Testing the logics for manipulating projects' tasks on localStorage
- Testing the DOM (event listeners)

Built with:
- Jest

2021-05-29 22:26 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__You've done really well so far. Here're the major highlights of this PR:__

- Your PR title, summary and commit messages are descriptive :+1: 
- You've created separate test files for each class or module :100: 
- Nice folder structure for the test files :ok_hand: 

__However, some changes that you are required to make before moving on to the next task. Please check my comments below and fix them as appropriate.__

### **Required Changes** :recycle: 

- [ ] For this project, we must check if all functions (especially the logic-related ones) are tested. However, I believe you can write more tests that will cover some functions in `src/js/logics/projectsList-Store.js` and `src/js/logics/tasksList-Store.js` scripts.

- [ ] Check the comments under the review.

### **Optional Changes** :yellow_circle: 
N/A


* * *
**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise.**

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. You can mention me (@teekaytech) so I can see your comments and respond._

_**Please make the required changes and submit another review request when you are done.**_

* * *
Regards,
**Taofeek Olalere**
__Cheers and happy coding :smiley:__

2021-05-29 22:26 UTC, teekaytech commented on __tests__/middleView.test.js
> +});
**Required**

- [ ] We must ensure that all test cases are passing. This particular one seems to be failing. Kindly check and fix the bug.

2021-05-31 19:50 UTC, umararshadbut requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @Milypm and @rloterh 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed.

##

Kindly work on the suggested changes  👇.
- [x] There is one test case that is failing as the previous code reviewer suggested. Please ensure all the test cases are passing. 

##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**Umair**
**Happy Coding :smiley:**

2021-06-01 04:22 UTC, rindrajosia requested changes
Changes Required :red_circle:
To Highlight: :angel:

- Good job by trying to fix bug related to test cases :+1: 

To improve :factory_worker: [REQUIRED]:

- [ ] There is one test case that is failing as the previous code reviewer suggested. Please ensure all the test cases are passing.
![1](https://user-images.githubusercontent.com/58552748/120264895-726cec00-c2a7-11eb-8663-531abd5e3cf5.gif)

Nice to have [OPTIONAL] :

- [ ] Please use **import** instead of **require** as you are using ES6 syntax.
- [ ] Make sure that you add test units for all functions in order to ensure that all of your functions work as expected.

That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

2021-06-01 04:22 UTC, rindrajosia commented on __tests__/leftView.test.js
> +const fs = require('fs');
[OPTIONAL] Please use import

2021-06-01 04:22 UTC, rindrajosia commented on __tests__/leftView.test.js
> +const path = require('path');
[OPTIONAL] Please use import

2021-06-01 04:22 UTC, rindrajosia commented on __tests__/middleView.test.js
> +const fs = require('fs');
[OPTIONAL] Please use import

2021-06-01 04:22 UTC, rindrajosia commented on __tests__/middleView.test.js
> +const path = require('path');
[OPTIONAL] Please use import

2021-06-01 04:22 UTC, rindrajosia commented on src/js/build.js
> +require('../css/style.css');
[OPTIONAL] Please use import

2021-06-01 04:22 UTC, rindrajosia commented on src/js/logics/projectsList-Store.js
> +    projects, projectObject, defaultProject, getProjects, addProject, editProject, deleteProject, findProject,
[OPTIONAL] Please add test units for: addProject, editProject, deleteProject **functions**

2021-06-01 18:45 UTC, SajjadAhmad14 approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

## Congratulations 🎉 Thank you for implementing changes suggested previously 🙏

### Happy Coding ☺️

## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

2021-06-01 19:02 UTC, merged